spring.application.name=pos

spring.profiles.active=prod

# Keep form submissions and rendered product names Unicode-safe.
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# ===============================


# ===============================
# FILE UPLOAD
# ===============================
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

#jwt secrets
jwt.secret=${JWT_SECRET:YjY0ZDI3M2I0YmE0YmI0YmI0YmI0YmI0YmI0YmI0YmI0YmI0YmI0YmI0YmI0YmI0YmI0YmI0Yg}

logging.level.org.hibernate.orm.boot.bind=TRACE
logging.level.org.springframework.orm.jpa=DEBUG