ALTER TABLE orders ADD COLUMN customer_id INTEGER NOT NULL DEFAULT 1 REFERENCES customer(id);
ALTER TABLE orders ADD COLUMN paid NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (paid >= 0);
ALTER TABLE orders ADD COLUMN remaining NUMERIC(10,2) NOT NULL GENERATED ALWAYS AS (total - paid) STORED;
